import React from 'react'
import createReactClass from 'create-react-class'
import i18n from 'i18n'

import { BaseMixin } from 'commons-mixins'
import { Select as UserSelect } from '../users'
import FormItem from '../FormItemView'

module.exports = createReactClass({
  displayName: 'License',

  mixins: [BaseMixin],

  render: function() {
    if (this.props.model.isNew()) {
      return this.renderItem(i18n('Count'), 'number', true)
    }

    return (
      <div className="license details">
        {this.renderUser()}
        {this.renderInvitee()}
        {this.renderGeneratedBy()}
      </div>
    )
  },

  renderInvitee: function() {
    if (this.props.model.get('user')) {
      return
    }

    return this.renderItem(i18n('Invitee'), 'invitee')
  },

  renderUser: function() {
    if (this.props.model.get('invitee')) {
      return
    }

    return (
      <FormItem label={i18n('User')}>
        {this.renderUserSelect()}
      </FormItem>
    )
  },

  renderItem: function(label, field, required) {
    return (
      <FormItem
        label={label}
        required={required}
        field={field}
        model={this.props.model}
      />
    )
  },

  renderGeneratedBy: function() {
    if (!this.props.model.get('generatedBy')) {
      return
    }

    return (
      <FormItem label={i18n('Generated by')}>
        {this.renderGeneratorLink()}
      </FormItem>
    )
  },

  renderGeneratorLink: function() {
    return (
      <a href="#" onClick={this.gotoGenerator}>
        {i18n('Show generator')}
      </a>
    )
  },

  gotoGenerator: function(ev) {
    ev.preventDefault()
    ev.stopPropagation()

    this.props.onGeneratorClick(this.props.model.get('generatedBy'))
  },

  renderUserSelect: function() {
    return (
      <UserSelect
        organization={this.props.model.get('organization')}
        value={this.props.model.get('user')}
        onChange={this.handleUserChange}
      />
    )
  },

  handleUserChange: function(user) {
    this.props.model.set('user', user)
  },
})



// WEBPACK FOOTER //
// ./src/admin/views/licenses/License.js